### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by zsoltk** [badoo/RIBs#96]
- [x] Automatic routing based on configurations 
- [x] Routing back stack
- [x] Tree structure persistence to Bundle (automatic)
- [x] Back stack persistence to Bundle (automatic)
- [x] Support for Android lifecycle
- [x] Template generator plugin with live code
- [x] Instrumentation test helpers to test RIBs in isolation
- [x] Android request code based result handling delivered to initiating RIB (Activity launching, permission requesting)
- [x] Overlay configurations
- [x] Ability to show dialogs
- [x] Ability to host a RIB in a dialog
- [x] Ability to provide scoped customisations to RIBs
- [x] Proper DI for Views
- [x] SavedInstanceState in constructor to avoid invalid temporary state until attach
- [x] Support for workflows
- [x] Full-screen portals (content or overlay)
- [x] View plugins
- [x] AndroidX
- [ ] BuildContext
- [ ] Ability to host RIBs as RecyclerView elements
- [ ] Support matching RIBs between routing configurations
- [ ] Support for transitions
- [ ] Tree change listener
- [ ] Tree visitor
- [ ] Allow creating and adding debug views per RIB to a drawer
- [ ] General cleanup
- [ ] General audit (code)
- [ ] General audit (tests)
- [ ] Documentation (code)
- [ ] Full tutorial coverage
- [ ] Best practices

**Comment by KirillMakarov** [comment]
Hello, is there any timeline when 1.0 is ready?

**Comment by NorbertSandor** [comment]
Is multiplatform support planned?
